### PR TITLE
Replace Mac OS X with macOS

### PR DESCRIPTION
**Pull request by Lokesh-Krishna**
Staying current.

### CODE REVIEW

**Comment by Lokesh-Krishna** [comment]
May I please know why this was closed? The same pull request was merged in Source Code Pro and Side Sans Pro.

**Comment by kenlunde** [comment]
Perhaps because the nature of this pull request was not unique to this particular repository, and it was easier to push the same "Mac OS X" or "OS X" → "macOS" change to multiple repositories.

**Comment by Lokesh-Krishna** [comment]
It was easy, yes. It was in fact my first pull request on GitHub. But it is nevertheless a change that improves the documentation, isn't it?

**Comment by frankrolf** [comment]
I closed it because the name “OS X” doesn't automatically cease to exist. Many users may still look for OS X, and not immediately refer to the system as macOS – many may not even update.
An improvement would be mentioning both names. 

(Closing it was not meant to hurt your feelings – sorry if it did.)

**Comment by Lokesh-Krishna** [comment]
I am so sorry about sounding entitled. I am not hurt and this explanation makes a lot of sense so thank you.  

I didn't mention both names because Apple itself seemed to be retconning the name out but you're right about that not really changing the fact that that's many people identify it and that others might not even update.

Once again, thank you for replying and explaining :)

**Pull request closed without merging**
